question1: 1/main.cpp  
	cd 1 && g++ main.cpp -o 1.out && mv 1.out  ../bin/
question2a: 2/main-a.cpp                   
	cd 2 && g++ main-a.cpp -o 2a.out && mv 2a.out  ../bin/
question2a: 2/main-b.cpp
	cd 2 && g++ main-b.cpp -o 2b.out && mv 2b.out  ../bin/
question3: 3/main.cpp
	cd 3 && g++ main.cpp -o 3.out && mv 3.out  ../bin/
clear: 
	cd 1 && rm *.o | cd 2 && rm *.o | cd 3 && rm *.o
